### PR TITLE
Add CMakeLists for all subprojects and root

### LINKED ISSUE #4: Root CMakeLists.txt?
I'd like to request a root CMakeLists.txt that builds everything at once (including placing the color schemes in /usr/share/color-schemes), preferably with flags to enable/disable building the seperate components. Having that would make it possible to create a single ebuild for Gentoo without making it super hacky.
I'd PR it myself but I know barely anything about cmake.

Thanks!

### PR DESCRIPTION
**Pull request by therealfarfetchd**
Closes #4

### CODE REVIEW

**Comment by n4n0GH** [comment]
Damn, okay. That was quick. Excited to see if you can get everything working :+1:

**Comment by therealfarfetchd** [comment]
Well, looks like it works.
I've tested everything but `make install` and kstyle since it can't find KF5 and I have no idea what I need to install for that.
Also not sure if `make uninstall` will delete everything since that's a extra-cmake-modules thing but I can't find where it gets added. Apparently you need `include(ECMUninstallTarget)` but that's nowhere to be found in the whole repo.

By default, everything but kstyle is on, you can toggle them with cmake arguments, for example `cmake .. -DWITH_KSTYLE=on -DWITH_COLOR_SCHEME=off` to build with kstyle and without color-scheme

**Comment by n4n0GH** [comment]
Dope. I'll look through this PR during the weekend and maybe I can figure out why kstyle is acting up. Thanks so far though! Really appreciate it!

**Comment by therealfarfetchd** [comment]
No problem!

**Comment by n4n0GH** [comment]
K, so; the code looks good but I won't merge. And I think you'll like the reason.

I was thinking, instead of just using a boring CMAKE in root, why not create a sweet installer that does the job?

scrot_20191117124923

I'm still thinking about a good way to auto-resolve the dependencies that way tho, maybe by checking what distro is running the script and have a pre-defined list of distro-specific names for the packages, then call the default package manager to try and install them and throw if something goes wrong.

What do you think about this?

**Comment by therealfarfetchd** [comment]
I don't think this is a good idea, at least not in place of merging this PR. First of all, you're never going to be able to make this support all distros if you want to install dependencies. Distro specific stuff should be left to the maintainers for the package on the respective distro. Similarly, this way you completely lose the advantage that installing it via package manager gives you, having a central way of updating and installing everything on the system. I don't think anyone would want to have to check an extra tool once in a while for updates. Also, doesn't the installer tackle a completely different issue than this PR, since this PR deals with compilation (and making packaging easier), while the installer is a user facing thing, for those who don't have hello in their repositories but don't want to mess with manually compiling it?

**Comment by n4n0GH** [comment]
> First of all, you're never going to be able to make this support all distros if you want to install dependencies

I can agree, that this would be a goliath task to tackle.

> Similarly, this way you completely lose the advantage that installing it via package manager gives you, having a central way of updating and installing everything on the system.

Arguably so, but I was planning to roll this out once I'm "done" with the theme, which would mean it'd be okay to set it up once and don't bother with it again.

> Also, doesn't the installer tackle a completely different issue than this PR

I don't think so; this PR makes it easier to install everything with a single command instead of compiling each package by itself. The installer aims to do the same; compile all packages. Both parts don't account for repositories or anything, correct me if I'm wrong.

Anyhow, I see the disadvantages overweigh the advantages and I'm probably going to move my idea to a seperate project instead.

Thank you for your honest opinion :+1:

**Pull request merged**
