### PR TITLE
Fix building plasma-theme

### PR DESCRIPTION
**Pull request by therealfarfetchd**

### CODE REVIEW

**Comment by therealfarfetchd** [comment]
And with that, we have [`kde-misc/hello`](https://git.therealfarfetchd.dev/ebuilds.git/tree/kde-misc/hello/hello-9999.ebuild) at https://git.therealfarfetchd.dev/ebuilds.git or https://github.com/therealfarfetchd/ebuilds!

**Comment by n4n0GH** [comment]
Ebuilds? That's for Gentoo, right?

**Comment by therealfarfetchd** [comment]
Yup

**Comment by n4n0GH** [comment]
Dang, that's cool stuff. I think I'll focus on updating the READMEs and Wiki tonight to get a proper installation guide going on.

**Pull request merged**
