### PR TITLE
Removed rounding corners when no decoration on window is present.

### PR DESCRIPTION
**Pull request by Acemond**
This addition will remove the rounding of the corners for all windows that don't have a decoration.

### CODE REVIEW

**Comment by Acemond** [comment]
Just noticed you already tried that option. What did go wrong with it?

**Comment by n4n0GH** [comment]
I think if you just use the detector for decorations, you'll remove the support to give applications that use CSD rounded corners. 

Try your patch with Firefox and remove its titlebar. 

27. Nov. 2019, 14:42 von notifications@github.com:

**Comment by Acemond** [comment]
I see. Well this doesn't impact me, so for now I'll continue with this branch. If I find a better solution I'll push it. You can delete this PR.

**Comment by n4n0GH** [comment]
Afaik the only way to get this working correctly is by using the logic we already discussed in #17

**Pull request closed without merging**
